import discord
from discord import app_commands
from discord.ext import commands
import os
import random
import string
from keep_alive import keep_alive  

# ================== CONFIG ==================
GUILD_ID = 1344670393092280481  # 🔹 заміни на ID твого сервера

# Канали
RULES_CHANNEL_ID = 1351689723369754634
INFO_CHANNEL_ID = 1425554175231529054
SUPPORT_CHANNEL_ID = 1411789053921202286
EXECUTORS_CHANNEL_ID = 1404173340125429792

# Ролі
STAFF_ROLES = ["Staff Team", "NexusVision Team"]
NEXUS_ONLY = ["NexusVision Team"]

# ================== BOT SETUP ==================
intents = discord.Intents.default()
intents.message_content = True
intents.members = True
bot = commands.Bot(command_prefix="?", intents=intents)

# ================== EVENTS ==================
@bot.event
async def on_ready():
    guild = discord.Object(id=GUILD_ID)
    await bot.tree.sync(guild=guild)
    print(f"✅ Bot {bot.user} is online and synced commands for guild {GUILD_ID}!")
    print(f"🔁 Total commands synced: {len(bot.tree.get_commands())}")

# ================== HELPERS ==================
def has_any_role(interaction: discord.Interaction, allowed_roles: list[str]) -> bool:
    """Check if user has any allowed role"""
    return any(role.name in allowed_roles for role in interaction.user.roles)

def generate_random_key():
    """Generate key format: XXXX-XXXX-XXXX-XXXX"""
    return "-".join(
        "".join(random.choices(string.ascii_uppercase + string.digits, k=4))
        for _ in range(4)
    )

# ================== COMMANDS ==================

# ---------- /changerole ----------
@bot.tree.command(
    name="changerole",
    description="Change a user's role (Staff/NexusVision only)",
    guild=discord.Object(id=GUILD_ID)
)
@app_commands.describe(user="Select a user", role="Select a role to assign")
async def changerole(interaction: discord.Interaction, user: discord.Member, role: discord.Role):
    if not has_any_role(interaction, STAFF_ROLES):
        await interaction.response.send_message("🚫 You don't have permission to use this command.", ephemeral=True)
        return

    try:
        await user.add_roles(role)
        await interaction.response.send_message(f"✅ {user.mention} has been given the role {role.mention}", ephemeral=True)
    except Exception as e:
        await interaction.response.send_message(f"❌ Failed to change role: {e}", ephemeral=True)

# ---------- /generatekey ----------
@bot.tree.command(
    name="generatekey",
    description="Generate a premium key (NexusVision only)",
    guild=discord.Object(id=GUILD_ID)
)
@app_commands.describe(
    active="Is the key active (True/False)?",
    days="Duration in days (7, 30, 90, 100000)"
)
async def generatekey(interaction: discord.Interaction, active: bool, days: int):
    if not has_any_role(interaction, NEXUS_ONLY):
        await interaction.response.send_message("🚫 You don't have permission to generate keys.", ephemeral=True)
        return

    if days not in [7, 30, 90, 100000]:
        await interaction.response.send_message("❌ Invalid duration. Choose 7, 30, 90, or 100000 days.", ephemeral=True)
        return

    key = generate_random_key()
    embed = discord.Embed(title="🔑 Key Generated", color=0x00ff88)
    embed.add_field(name="Key", value=f"`{key}`", inline=False)
    embed.add_field(name="Active", value=str(active), inline=True)
    embed.add_field(name="Days", value=str(days), inline=True)
    embed.set_footer(text=f"Generated by {interaction.user.display_name}")
    await interaction.response.send_message(embed=embed, ephemeral=True)

# ---------- /get_ar2_script ----------
@bot.tree.command(
    name="get_ar2_script",
    description="Get the AR2 Script",
    guild=discord.Object(id=GUILD_ID)
)
async def get_ar2_script(interaction: discord.Interaction):
    script = '```lua\nloadstring(game:HttpGet("https://raw.githubusercontent.com/UnicoreRoblox/Unicore/refs/heads/main/ApocalypseRising2.luau"))()\n```'
    await interaction.response.send_message(script, ephemeral=True)

# ---------- /get_universal_script ----------
@bot.tree.command(
    name="get_universal_script",
    description="Get the Universal Script",
    guild=discord.Object(id=GUILD_ID)
)
async def get_universal_script(interaction: discord.Interaction):
    script = '```lua\nloadstring(game:HttpGet("https://raw.githubusercontent.com/NightFallScript/Unicore/refs/heads/main/DoorsUnicore"))()\n```'
    await interaction.response.send_message(script, ephemeral=True)

# ---------- /rules ----------
@bot.tree.command(
    name="rules",
    description="Link to rules channel",
    guild=discord.Object(id=GUILD_ID)
)
async def rules(interaction: discord.Interaction):
    channel = bot.get_channel(RULES_CHANNEL_ID)
    if channel:
        await interaction.response.send_message(f"📜 Rules are here: {channel.mention}", ephemeral=True)
    else:
        await interaction.response.send_message("❌ Rules channel not found.", ephemeral=True)

# ---------- /info ----------
@bot.tree.command(
    name="info",
    description="Link to info channel",
    guild=discord.Object(id=GUILD_ID)
)
async def info(interaction: discord.Interaction):
    channel = bot.get_channel(INFO_CHANNEL_ID)
    if channel:
        await interaction.response.send_message(f"ℹ️ Info is here: {channel.mention}", ephemeral=True)
    else:
        await interaction.response.send_message("❌ Info channel not found.", ephemeral=True)

# ---------- /support ----------
@bot.tree.command(
    name="support",
    description="Link to support channel",
    guild=discord.Object(id=GUILD_ID)
)
async def support(interaction: discord.Interaction):
    channel = bot.get_channel(SUPPORT_CHANNEL_ID)
    if channel:
        await interaction.response.send_message(f"🛠️ Support is here: {channel.mention}", ephemeral=True)
    else:
        await interaction.response.send_message("❌ Support channel not found.", ephemeral=True)

# ---------- /support_executors ----------
@bot.tree.command(
    name="support_executors",
    description="Link to executors channel",
    guild=discord.Object(id=GUILD_ID)
)
async def support_executors(interaction: discord.Interaction):
    channel = bot.get_channel(EXECUTORS_CHANNEL_ID)
    if channel:
        await interaction.response.send_message(f"⚙️ Executors are here: {channel.mention}", ephemeral=True)
    else:
        await interaction.response.send_message("❌ Executors channel not found.", ephemeral=True)

# ---------- /help ----------
@bot.tree.command(
    name="help",
    description="List all available commands",
    guild=discord.Object(id=GUILD_ID)
)
async def help_command(interaction: discord.Interaction):
    embed = discord.Embed(title="📖 Command List", color=0x2b2d31)
    embed.add_field(name="/get_ar2_script", value="Get AR2 Script", inline=False)
    embed.add_field(name="/get_universal_script", value="Get Universal Script", inline=False)
    embed.add_field(name="/rules", value="Show rules channel", inline=False)
    embed.add_field(name="/info", value="Show info channel", inline=False)
    embed.add_field(name="/support", value="Show support channel", inline=False)
    embed.add_field(name="/support_executors", value="Show executors channel", inline=False)
    embed.add_field(name="/changerole", value="Change user role (Staff/NexusVision only)", inline=False)
    embed.add_field(name="/generatekey", value="Generate a key (NexusVision only)", inline=False)
    await interaction.response.send_message(embed=embed, ephemeral=True)

# ---------- Legacy ?scripts ----------
@bot.command(name="scripts")
async def scripts(ctx):
    embed = discord.Embed(
        title="📜 Script Panel",
        description="This script panel is for the project : **Unicore**\n\n"
                    "Use the buttons below to get Universal Script or AR2 Script",
        color=0x2b2d31
    )

    view = discord.ui.View()

    async def universal_callback(interaction: discord.Interaction):
        script = '```lua\nloadstring(game:HttpGet("https://raw.githubusercontent.com/NightFallScript/Unicore/refs/heads/main/DoorsUnicore"))()\n```'
        await interaction.response.send_message(script, ephemeral=True)

    universal_button = discord.ui.Button(label="📜 Get Universal Script", style=discord.ButtonStyle.secondary)
    universal_button.callback = universal_callback
    view.add_item(universal_button)

    async def ar2_callback(interaction: discord.Interaction):
        script = '```lua\nloadstring(game:HttpGet("https://raw.githubusercontent.com/UnicoreRoblox/Unicore/refs/heads/main/ApocalypseRising2.luau"))()\n```'
        await interaction.response.send_message(script, ephemeral=True)

    ar2_button = discord.ui.Button(label="📜 Get AR2 Script", style=discord.ButtonStyle.secondary)
    ar2_button.callback = ar2_callback
    view.add_item(ar2_button)

    await ctx.send(embed=embed, view=view)

# ================== RUN ==================
keep_alive()
bot.run(os.getenv("TOKEN"))
